'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useAppwrite } from '@/hooks/useAppwrite';
import { DailyEntry } from '@/types';
import { syncMileageContinuity } from '@/utils/mileage';

export default function Dashboard() {
  const { entries, settings, isLoaded, addEntry, deleteEntry, migrateFromLocal, user, recalculateAllMileage, isSyncing } = useAppwrite();
  const [newDate, setNewDate] = useState(new Date().toISOString().split('T')[0]);
  const [hasLocalData, setHasLocalData] = useState(false);

  useEffect(() => {
    const local = localStorage.getItem('uber-entries');
    if (local && local !== '[]') {
      setHasLocalData(true);
    }
  }, []);

  const getLatestKmEnd = () => {
    if (entries.length === 0) return 0;
    const sorted = [...entries].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    return sorted[0].kmEnd;
  };

  const handleAddDay = async () => {
    const exists = entries.find(e => e.date === newDate);
    if (exists) {
      alert('Există deja o intrare pentru această dată!');
      return;
    }

    const newEntry: DailyEntry = {
      id: '', // Will be generated by Appwrite
      date: newDate,
      kmStart: getLatestKmEnd(),
      kmEnd: getLatestKmEnd(), 
      tripCount: 0,
      startTime: '08:00',
      endTime: '20:00',
      route: settings.defaultZone
    };

    await addEntry(newEntry);
  };

  const removeEntry = async (id: string) => {
    if (confirm('Sigur vrei să ștergi această zi?')) {
      await deleteEntry(id);
    }
  };

  const handleMigrate = async () => {
    if (confirm('Dorești să imporți datele salvate local în Cloud? (Aceasta se face o singură dată)')) {
      await migrateFromLocal();
      setHasLocalData(false);
      localStorage.removeItem('uber-entries');
      localStorage.removeItem('uber-settings');
    }
  };

  if (!isLoaded) return <div className="container">Incarcare...</div>;

  return (
    <div className="container">
      <div className="no-print">
        {hasLocalData && (
          <div className="card" style={{ backgroundColor: '#fef3c7', borderColor: '#f59e0b', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <p style={{ fontSize: '0.9rem', color: '#92400e', margin: 0 }}>
              Ai date salvate pe acest dispozitiv care nu sunt în Cloud.
            </p>
            <button className="btn btn-primary" onClick={handleMigrate} style={{ width: 'auto', padding: '0.4rem 0.8rem', fontSize: '0.8rem', backgroundColor: '#d97706' }}>
              Migrează în Cloud
            </button>
          </div>
        )}

        <header style={{ marginBottom: '2rem', textAlign: 'center' }}>
          <h1 style={{ fontSize: '1.75rem', marginBottom: '0.5rem' }}>Activitate Uber</h1>
          <p style={{ opacity: 0.7, fontSize: '0.9rem' }}>{settings.carBrand} {settings.carModel} • {settings.carPlate}</p>
          <p style={{ fontSize: '0.8rem', opacity: 0.5 }}>Utilizator: {user?.email}</p>
        </header>

        <section style={{ marginBottom: '2rem' }}>
          <div className="card" style={{ display: 'flex', flexWrap: 'wrap', gap: '1rem', alignItems: 'flex-end' }}>
            <div className="form-group" style={{ flex: 1, marginBottom: 0 }}>
              <label>Selectează Data</label>
              <input 
                className="form-control" 
                type="date" 
                value={newDate} 
                onChange={(e) => setNewDate(e.target.value)} 
              />
            </div>
            <button className="btn btn-primary" onClick={handleAddDay} style={{ width: 'auto', flex: 1 }}>
              ➕ Adaugă Zi
            </button>
          </div>
        </section>

        <section>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem', flexWrap: 'wrap', gap: '1rem' }}>
            <h2 style={{ fontSize: '1.25rem' }}>Istoric Recent</h2>
            <div style={{ display: 'flex', gap: '0.5rem' }}>
              <button 
                className="btn" 
                onClick={recalculateAllMileage} 
                disabled={isSyncing || entries.length === 0}
                style={{ width: 'auto', padding: '0.5rem 1rem', fontSize: '0.8rem', backgroundColor: 'var(--input)' }}
              >
                {isSyncing ? '⏳ Sincronizare...' : '🔄 Sincro KM'}
              </button>
              <Link href="/report" className="btn btn-primary" style={{ width: 'auto', padding: '0.5rem 1rem', fontSize: '0.8rem' }}>
                Vezi Foaia de Parcurs
              </Link>
            </div>
          </div>

          {isSyncing && (
            <div className="card" style={{ textAlign: 'center', backgroundColor: '#eff6ff', color: '#1d4ed8', fontSize: '0.9rem' }}>
              Se recalculează continuitatea kilometrajului pentru toată baza de date. Te rugăm să aștepți...
            </div>
          )}

          {entries.length === 0 ? (
            <div className="card" style={{ textAlign: 'center', opacity: 0.6 }}>
              Nu există date introduse încă.
            </div>
          ) : (
            [...entries].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()).map(entry => (
              <div key={entry.id} className="card" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                  <div style={{ fontWeight: 800 }}>{new Date(entry.date).toLocaleDateString('ro-RO', { weekday: 'short', day: 'numeric', month: 'long' })}</div>
                  <div style={{ fontSize: '0.85rem', opacity: 0.8 }}>
                    {entry.kmStart} km → {entry.kmEnd} km ({entry.kmEnd - entry.kmStart} km)
                  </div>
                  <div style={{ fontSize: '0.85rem', opacity: 0.8 }}>
                    {entry.tripCount} curse • {entry.fueling ? `Alimentat: ${entry.fueling.liters}L` : 'Fără alimentare'}
                  </div>
                </div>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <Link href={`/edit/${entry.id}`} className="btn" style={{ width: 'auto', backgroundColor: 'var(--input)', fontSize: '0.8rem' }}>
                    Edit
                  </Link>
                  <button onClick={() => removeEntry(entry.id)} className="btn" style={{ width: 'auto', backgroundColor: '#fee2e2', color: '#ef4444', fontSize: '0.8rem' }}>
                    🗑️
                  </button>
                </div>
              </div>
            ))
          )}
        </section>
      </div>
    </div>
  );
}
